// PLEASE DO NOT EDIT THIS FILE
// ANY CODE YOU WISH TO ADD SHOULD BE INCLUDED IN `main.cpp` AND OTHER SOURCE FILES.

#include "CCMplugin.hpp"

#define _xstr(s) #s
#define _str(s) _xstr(s)

_MAIN_CLASS* instance;

_MAIN_CLASS::_MAIN_CLASS() : CCMplugin(
    icu::UnicodeString::fromUTF8(icu::StringPiece(_str(CCM_PLUGIN_NAME))),
    icu::UnicodeString::fromUTF8(icu::StringPiece(_str(CCM_PLUGIN_DESCRIPTION))),
    icu::UnicodeString::fromUTF8(icu::StringPiece(_str(CCM_PLUGIN_VENDOR))),
    {CCM_PLUGIN_VERSION_MAJOR, CCM_PLUGIN_VERSION_MINOR, CCM_PLUGIN_VERSION_BUILD},
    CCM_PLUGIN_TYPE,
    CCMuuid::fromString(_str(CCM_PLUGIN_UUID))
)
{
}

EXPORT CCMplugin* getPluginInstance()
{
    if(instance == nullptr)
        instance = new _MAIN_CLASS();
    
    return instance;
}

// Get rid of _xstr, and _str macros. They aren't needed anymore...
#undef _xstr
#undef _str

